{% set name = "srsly" %}
{% set version = "2.3.2" %}
{% set sha256sum = "f78eaef8d982e98921ce026d4205e652a9333137259f0b621f5c7b579e746e9d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py2k or py35]


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython
  run:
    - python

test:
  imports:
    - srsly
    - srsly.tests
  requires:
    - pytest
    - pytz
    - mock
    - numpy >=1.15.0
  commands:
    - python -m pytest --tb=native --pyargs {{ name }}

about:
  home: http://github.com/explosion/srsly
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Modern high-performance serialization utilities for Python

  doc_url: https://github.com/explosion/srsly
  dev_url: https://github.com/explosion/srsly

extra:
  recipe-maintainers:
    - ines
    - honnibal
    - adrianeboyd
